karaxnim/karax

src/components.nim, src/karaxdsl.nim
The change to components fixes `do:` ambiguity, the change to karaxdsl  fixes an `Expected a node of kind nnkDo, got nnkStmtList` error in buildHtml
=> Fix some issues with v0.17

src/vdom.nim
I am not sure if there is a reason for their ommision
Also, onsubmit is defined in dom.nim, but not oninput, maybe because it works only on some elements?
=> Support submit and input event in the vdom

src/karax.nim, src/kdom.nim
This PR adds functionality required to do stuff like [this](https://github.com/bluenote10/KaraxExamples/tree/master/DemoTransitionGroups). Changes:
* Adds a post render callback. Transitions like these require to extract DOM information at a "post-layout" but "pre-paint" point in time, which is where the callback is called. [*]
* Added the missing `transform` property to styles.
* Added missing fields of the bounding rect object. Also changed the type to float, because the bounding rect values can be floats.
* Exposed `reqFrame` for client use (necessary for scheduling "post-paint" events).
[*] Similar to the lifecycle hooks in React, or the transition-groups in Vue.
=> Enable list transitions

karax/vdom.nim
Update verbatim VNodeKind processing for static HTML generating.
```
if n.kind == VNodeKind.text:
result.addEscaped(n.text)
elif n.kind == VNodeKind.verbatim:
result.add(n.text)
```
=> update verbatim for static HTML

karax/vdom.nim
I went with the most consistent method (relative to the code around it) I could come up with, while keeping the code simple and efficient. I considered using regex, but found the `tokenize` function which solves this problem quite nicely. It works because all style enums use camelCasing, so `marginTop` -> `margin-top`.
Minor cosmetic nitpick is there will always be an extra space at the end (`style="margin-top: 1em; "`), but I couldn't come up with a short solution that doesn't use a temporary variable, stripping `result`, or keeping an index variable.
=> Add support for rendering styles to string

karax/karax.nim
/cc @araq this seems to:
* fix #121 (as well as my original problem from which this was a reduced case)
also works with reordering eg: `velements = velements[2..^1]` => `velements = @[velements[2], velements[4], velements[3]]`
* fix #56 (in particular https://github.com/pragmagic/karax/issues/56#issuecomment-531099826 which more obviously exhibits the bug)
=> fix #121 fix #56 

karax/vdom.nim
List of void elements pulled from specs here: https://html.spec.whatwg.org/multipage/syntax.html#void-elements
=> Self-closing tags (#133)

karax/vstyles.nim
example use case: allow client code to write this:
```nim
proc toCss*(a: string): VStyle =
#[
can be simpler than this when porting existing code to karax:
{cssFloat: "left", borderColor:"red"}
"float:left borderColor:red"
style(StyleAttr.color, col) => "color:red".toCss
note: this doesn't seem related: https://github.com/pragmagic/karax/pull/102
]#
result = newJSeq[cstring]()
for ai in a.split(";"):
var ai = ai.strip
if ai.len == 0: continue
let aj = ai.strip.split(":", maxsplit=1)
result.setAttr(aj[0], aj[1])
```
(which could later be part of karax), to use a string directly instead of an enum, and can be simpler than this when porting existing code to karax.
=> make vstyles.setAttr kstring overload public

examples/hellostyle.nim, karax/vstyles.nim
see ` karun -r $nim_D/karax/examples/hellostyle.nim`
the last commit makes sure toCss also works with nim c, eg in following example:
~~(note: see followup PR to fix pre-existing bug to make this work, see https://github.com/pragmagic/karax/issues/153 EDIT: fixed in recent PR)~~
`nim r main`
```nim
when true:
import karax / [karaxdsl, vdom, vstyles]
let node = buildHtml(tdiv):
let myStyle = "width: 25%; border: 1px".toCss
tdiv(style = myStyle):
text ""
echo $node
```
/cc @araq please let me know if you can think of a way to allow writing directly
```nim
tdiv(style = "width: 25%; border: 1px"): discard
tdiv(style = "width: 25%; border: 1px".toCss): discard
```
without resorting to `converter`, otherwise this is ready for review
=> add toCss: allows tdiv(style = "font-style: oblique; color: pink".toCss)

karax/vdom.nim
Since _HTML 5.1_
Spec: https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element
=> Add picture tag

karax/tools/karun.nim
Currently if you run `karun -w -r thing.nim` it will refresh the browser via websocket the first time `thing.nim` is changed, but not for subsequent changes.
=> Make 'karun -w -r ...' do watching for more than one iteration

karax/karax.nim
I agree with @planetis-m, `kout` tends to be much more useful for print style debugging is when compared with `echo`, and sometimes is the best way to deal with printing JsObjects from external JS libraries as well.
=> Remove kout deprecation (https://github.com/karaxnim/karax/issues/182)

tests/tester.nim
This should allow the tester code to run on Nim 1.2, see https://github.com/karaxnim/karax/pull/199#discussion_r634235176
=> reworked tester to use process directly

examples/slider.nim
when use `postRender` get the right value by use `node.defaultValue`, well in this case we dont need postRender
=> fix #118, or call right example

karax.nimble, karax/tools/static_server.nim
This supersedes #217 
Updated `dotenv` to 2.0.0, which has hanged its API for loading environment files. I've also added a version constraint to the Nimble file.
=> Updated dotenv dependency to 2.0.0.

examples/ajax/ajax.nim, examples/ajax/styles.css, karax/jjson.nim
This PR adds a simple example that uses ajaxGet to load the nim package list and show a searchable list of packages
I also added two new procs to jjson that seemed useful enough to include there, and are used in the example
=> add example using kajax to load data

karax/karax.nim, readme.md
Change `defined(release)` to `defined(debugKaraxSame)` as discussed in #241. I also added a small table to the readme documenting the different flags.
=> Add new flag; update readme

karax/vdom.nim
Checked against the [MDN list](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference) of valid, non-deprecated tags. Supercedes #235. Ready to merge
=> Add missing html tags

karax/karax.nim, karax/vdom.nim, karax/vstyles.nim
Adds a styleVersion field that tracks the rendered styles version, so the vstyle can be reused. As discussed in #210
=> Adds a styleVersion field to VNode

karax/vstyles.nim
when called on a string that is not structured correctly (e.g. using `=` instead of `:` see #250)
=> Add better error message to toCss

karax/jstrutils.nim, karax/karax.nim
I noticed `hashPart` ate the query string, which is not good for routing, so I decided to fix it. `RouterData` now has `hashPart` and `queryString`. One has the hash "path", the other has the search string
=> Add query string and fix hash

karax/karax.nim
This PR adds a `reapplyEvents` proc (called during `moveDom`) that removes event handlers from the attached dom element, then reapplies them pointing to the new vnode. This is necessary because after diffing the new vnode now owns the attached dom element.
This approach feels a little costly as the handlers must be replaced on each diff. I initially tried to instead attach the vdom to the dom node so that the event wrapper could use that, and the vnode could be updated, but that did not work. What are your thoughts @Araq?
This would solve #254 and #117
=> Fix vnode event move

readme.md
Fixed a typo in `readme.md`.
Change: `avaible` -> `available`.
=> fix: typo in readme.md

karax/karax.nim
Closes https://github.com/karaxnim/karax/pull/160 and https://github.com/karaxnim/karax/issues/200.
Template's seem [well-supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) and I haven't found any problems testing locally. 
This also avoids the problem with #160 mentioned in this [reply](https://github.com/karaxnim/karax/issues/200#issuecomment-846568814) and properly handles children.
=> fix(#200): use template element for verbatim

karax.nimble, karax/karax.nim, karax/vdom.nim
ok, so here it is. I did the same test as in the .yml file so it should be all good.
edit: I ticked the version number, hope thats correct
=> propper svg/math elements

readme.md
fix GitHub workflow badge URL.
See https://github.com/badges/shields/issues/8671
> You need to update your badge URL from
> https://img.shields.io/github/workflow/status/<user>/<repo>/Run%20Tests
> to
> https://img.shields.io/github/actions/workflow/status/<user>/<repo>/test.yml?branch=main
=> fix GitHub workflow badge URL

karax/karax.nim
This reverts commit 8e0f471e6368c57645909f10cbcb64b0df037a09. (see issue #273 )
=> Revert "fix(#200): use template element for verbatim (#270)"

karax/karax.nim, karax/karaxdsl.nim
There is currently no easy way to surpress redraw just for one specific handler (probably because it isnt needed very often).
You can `kxi.surpressRedraw = true` inside your handler, but then there is no way to set it back afterwards.
The only way currently is using `addEventListener` manually, which isnt very elegant.
So I added `addEventHandlerNoRedraw` procs to `karax.nim` and the `.noredraw.` pragma to the dsl syntax.
Now you just need to do:
```nim
buildHtml(..):
...
proc onclick {.noredraw.} =
dostuff
...
```
or
```nim
proc onclick(e: Event, n: VNode) {.noredraw.} =
dostuff
```
maybe this would be nice to have in the repo
=> feature suggestion: {.noredraw.} pragma

karax/karax.nim
Issue https://github.com/karaxnim/karax/issues/61 is also valid for `textarea`. Therefore, a fix similar to https://github.com/karaxnim/karax/pull/201 is proposed in this PR.
=> Add reactivity to the textarea kind VNodes.

karax/kdom_impl.nim, tests/domEventTests.css, tests/domEventTests.nim
There was a partial implementation of just the Touch objects. Added the extra scaffolding for the event listeners and tests based on the existing drag tests.
=> add touch events and tests

karax/kajax.nim
fixes #291
since Nim support JS lambda lifting. The meaning of `this` has changed in the closure functions. It represents captured variables rather than binding objects.
`--legacy:jsnolambdalifting` should work as well.
=> fixes #291; incorrect `this` access

readme.md
=> doc(readme): fix karun ex. rendered in single line

karax/vdom.nim
Add events from mozilla's documentation for the `<audio>` and `<video>` tags, [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio#events) and [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/video#events).
Fixes: #295
=> Add audio/video events to EventKind enum
