- src/vdom.nim
> Add oncontextmenu event

- readme.rst
Is travis building already activated?
> Added travis link

- src/kajax.nim
- src/kdom.nim
- src/localstorage.nim
Used `re"(?<!\.)}"` in karax directory. I run the tester and all but the last commands succeeded (no node.js found).
> Fix ending .} of pragmas

- karax/errors.nim
This proc could help on Styling an app that appears and disappears errors tags next to the input component.
> Adding hasError method

- .gitignore
- karax/tools/karun.nim
minor changes to make command line option `--css` works in karun
>  make --css works in karun

- karax/karaxdsl.nim
> Don't choke on nnkDotExpr nodes

- karax/kajax.nim
- karax/vdom.nim
Added uploadFile with progress and a path tag of VNodeKind which uses in svg
> add uploadFile and a path tag

- readme.rst
It wasn't clear to me that Karax could be used on the server and I thought some docs would help others realize the same.
> Add docs explaining server side HTML rendering

- karax/tools/karun.nim
Remove ugly debug echo (sorry)
> Remove ugly debug echo

- karax/tools/karun.nim
Add common meta tag for Mobile first development
> Common meta tag for Karun

- karax/karaxdsl.nim
Change proposed in https://github.com/pragmagic/karax/issues/61#issuecomment-522233192
> Reactive value

- examples/todoapp/todoapp.nim
1."onAllDone" callback fixation.
Because the callback deletes all tasks instead of making them done, fixed.
2.Retouching checkbox and label property.
Because the checkbox didn't work and label did'nt affect the checkbox, I moved the callback  and 
rename label's "for".
3.Adding Global var "doneswitch" for convinience.
I guess the button should be able to make "All Done" and "All Undone". So make it, interfaced with the checkbox's display.
> 3 tiny changes for "All Done" button.

- .gitignore
- karax.nimble
- karax/tools/karun.nim
- karax/tools/karun.nims
- karax/tools/static_server.nim
> add static server,websocket refresh watching mode

- karax/tools/karun.nim
watch mode ignore precompile styles files.
> watch ignore precompile style lang

- karax/vdom.nim
see https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent
> add transition events

- examples/login.nim
In `login.nim` example was a bug with a password entering. When I entered a password after entering a username the `login` button didn't work. The problem was in 
```nim
if x.text.isNil or x.text == "":
...
```
I did this:
```nim
if x.text == "":
...
```
And it works now.
> Fixed the error with password

- .travis.yml
- karax/tools/static_server.nim
Changed existsFile to fileExists and existsDir to dirExists.
> Get rid of annoying deprecation warnings

- karax/tools/static_server.nim
Also attempt to fix `handleFileRequest` which was copy pasted from [jester.nim](https://github.com/dom96/jester/blob/master/jester.nim#L319) wrongly. Changes made:
- Cleanup imports, use `std`
- Fix logging: add consolelogger, set filter in release mode
- Run `nimpretty` on the file
- option around `RawHeaders` was removed as it served no purpose.
- `publicUrl` env variable removed, it is also absent from jester
- Smaller cleanups not worth mentioning
> Refactor static_server

- karax/vdom.nim
This commit adds all svg elements to Vdom
> add all svg elements acording to the standard

- karax/karax.nim
This patch changes `dodraw` so that:
* `kxi.renderId` is only used to block queuing of multiple `dodraw` calls
* A new `kxi.rendering` blocks `dodraw` running when a rerender is happening, and if so queue up a new `dodraw`
> Fix issue #192 (Strange edge case with onblur not causing an update)

- guide/Installation.md
- guide/Introduction.md
- tests/tester.nim
Created a new `guide` folder that has a guide written out in Markdown. Not much to see there, but I also updated `tester.nim` so that it tries to compile all of the snippets in the guide. Putting this out there for feedback on if this is the "correct" way of doing things.
> Guide Introduction

- karax/karax.nim
- karax/kdom.nim
- karax/kdom_impl.nim
Not sure how to test this change, so any advice is welcome.
Fixes #186
Fixes #61
> Make input value and checked state get updated

- examples/carousel/carousel.nim
fix #112 "carousels" example doesn't work
> fix #112 "carousels" example doesn't work

- karax/karaxdsl.nim
- tests/scope.nim
> handle block

- karax/tools/static_server.nim
ref https://github.com/nim-lang/Nim/pull/20951
> remove cgi deps

- karax.nimble
A new tag will be appreciated.
> bump to 1.2.3 so that latest tagged version works with 2.0

- experiments/trello/knete.nim
- karax/karaxdsl.nim
> deprecate flathtml macro

- karax/karax.nim
similar to toDisabled/toSelected/toChecked, but for attributes like contenteditable. Related #239 . Ready to merge
> Add "toAttr"

- readme.md
Related #243 . Slightly modified
> Add explanation of reactivity to readme

- karax.nimble
1.3.2 did not have the correct version number in the nimble file
> Update version number in nimble file

- karax/kdom_impl.nim
Problem described here: https://github.com/karaxnim/karax/issues/284
> fix BigInt conversion error, xOffset/yOffset from int64 to int
